name: jenkins-status

on:
  push:
    branches:
      - Dev
      - QA
      - main

  pull_request:
    branches:
      - Dev
      - QA
      - main

jobs:
  jenkins-status:
    runs-on: ubuntu-latest

    steps:
      - name: Determine branch
        id: branch
        run: |
          if [ "$GITHUB_EVENT_NAME" = "pull_request" ]; then
            BRANCH_NAME="${GITHUB_BASE_REF}"
          else
            BRANCH_NAME="${GITHUB_REF_NAME}"
          fi

          echo "Branch Name: $BRANCH_NAME"
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

      - name: Wait for Jenkins build
        env:
          JENKINS_URL: ${{ secrets.JENKINS_URL }}
          JENKINS_USER: ${{ secrets.JENKINS_USER }}
          JENKINS_TOKEN: ${{ secrets.JENKINS_TOKEN }}
        run: |

          JOB_PATH="job/jenkins-deploy/job/${BRANCH_NAME}"

          echo "Waiting for Jenkins build on branch: ${BRANCH_NAME}"

          # Give Jenkins time to start
          sleep 20

          LAST_BUILD=$(curl -s -u "$JENKINS_USER:$JENKINS_TOKEN" \
            "$JENKINS_URL/$JOB_PATH/lastBuild/api/json")

          BUILD_NUMBER=$(echo "$LAST_BUILD" | jq -r '.number')

          if [ "$BUILD_NUMBER" = "null" ] || [ -z "$BUILD_NUMBER" ]; then
            echo "No Jenkins build found."
            exit 1
          fi

          echo "Tracking Jenkins Build #$BUILD_NUMBER"

          while true
          do
              STATUS=$(curl -s -u "$JENKINS_USER:$JENKINS_TOKEN" \
                "$JENKINS_URL/$JOB_PATH/$BUILD_NUMBER/api/json")

              BUILDING=$(echo "$STATUS" | jq -r '.building')

              if [ "$BUILDING" = "false" ]; then
                  break
              fi

              echo "Still building..."
              sleep 10
          done

          RESULT=$(echo "$STATUS" | jq -r '.result')

          echo "Build Result: $RESULT"

          if [ "$RESULT" != "SUCCESS" ]; then

              echo ""
              echo "======================================"
              echo "JENKINS BUILD FAILED"
              echo "======================================"

              curl -s \
                -u "$JENKINS_USER:$JENKINS_TOKEN" \
                "$JENKINS_URL/$JOB_PATH/$BUILD_NUMBER/consoleText" | tail -60

              exit 1
          fi

          echo "Jenkins Build Successful."